# Generated by Django 4.1.7 on 2023-02-19 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Навазние')),
                ('number_pages', models.PositiveBigIntegerField(blank=True, verbose_name='Количество страниц')),
                ('writer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
        ),
    ]
